/**
 * components/footer.ts — Page number + branding footer.
 * Horizontal rule above, left: branding text, right: "Page N of M".
 */

import { PDFPage } from 'pdf-lib'
import {
  PAGE_WIDTH,
  MARGIN_BOTTOM,
  MARGIN_LEFT,
  MARGIN_RIGHT,
  COLORS,
  type Fonts,
  drawLine,
} from '../renderer'

export function drawFooter(
  page: PDFPage,
  fonts: Fonts,
  pageNumber: number,
  totalPages: number,
) {
  const footerTop = MARGIN_BOTTOM + 20
  const textY = MARGIN_BOTTOM + 6

  // Horizontal rule above footer
  drawLine(page, MARGIN_LEFT, footerTop, PAGE_WIDTH - MARGIN_RIGHT, footerTop, {
    color: COLORS.borderDefault,
    thickness: 1,
  })

  // Left: branding
  const brandText = 'Generated by LetSorted \u00B7 letsorted.co.uk'
  page.drawText(brandText, {
    x: MARGIN_LEFT,
    y: textY,
    size: 8,
    font: fonts.regular,
    color: COLORS.textMuted,
  })

  // Right: page numbers
  const pageText = `Page ${pageNumber} of ${totalPages}`
  const pageTextWidth = fonts.regular.widthOfTextAtSize(pageText, 8)
  page.drawText(pageText, {
    x: PAGE_WIDTH - MARGIN_RIGHT - pageTextWidth,
    y: textY,
    size: 8,
    font: fonts.regular,
    color: COLORS.textMuted,
  })
}
