import { prisma } from '@/lib/prisma'
import Link from 'next/link'

// ── Grade colour ───────────────────────────────────────────────────────────────

function gradeColour(grade: string | null) {
  if (!grade) return 'text-gray-600 bg-gray-50'
  if (grade === 'Excellent' || grade === 'Good') return 'text-green-700 bg-green-50'
  if (grade === 'Fair') return 'text-amber-700 bg-amber-50'
  if (grade === 'Poor') return 'text-orange-700 bg-orange-50'
  return 'text-red-700 bg-red-50'
}

function formatDate(d: Date) {
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default async function VerifyReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params

  const report = await prisma.financialReport.findUnique({
    where: { verificationToken: token },
    select: {
      id: true,
      status: true,
      totalScore: true,
      grade: true,
      reportType: true,
      createdAt: true,
      verificationToken: true,
    },
  }).catch(() => null)

  // ── Not found / not completed ──────────────────────────────────────────────

  if (!report || report.status !== 'COMPLETED' || report.totalScore === null) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="max-w-sm text-center">
          <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </div>
          <h1 className="text-gray-900 font-bold text-xl mb-2">Report not found</h1>
          <p className="text-gray-500 text-sm">
            This report could not be verified. The link may be invalid or the report may have been deleted.
          </p>
          <Link href="/" className="mt-6 inline-block text-sm text-green-600 hover:text-green-700 font-medium transition-colors">
            ← letsorted.co.uk
          </Link>
        </div>
      </div>
    )
  }

  // ── Verified ───────────────────────────────────────────────────────────────

  const colourCls = gradeColour(report.grade)

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-md mx-auto">

        {/* Logo */}
        <div className="text-center mb-8">
          <Link href="/" className="text-[#0f1a0f] font-bold text-xl tracking-tight hover:opacity-80 transition-opacity">
            LetSorted
          </Link>
        </div>

        {/* Verified badge */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 mb-4 text-center">
          <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-3">
            <svg className="w-8 h-8 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <h1 className="text-gray-900 font-bold text-xl mb-1">This report is authentic</h1>
          <p className="text-gray-400 text-sm">
            Generated by LetSorted on {formatDate(report.createdAt)}
          </p>
        </div>

        {/* Score card */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 mb-4">
          <div className="flex items-center gap-4 mb-4">
            <div className={`${colourCls} rounded-xl px-5 py-3 text-center min-w-[80px]`}>
              <div className="font-bold text-3xl leading-none">{report.totalScore}</div>
              <div className="text-xs font-medium mt-0.5 opacity-70">/ 100</div>
            </div>
            <div>
              <div className={`font-bold text-xl ${colourCls.split(' ')[0]}`}>{report.grade}</div>
              <div className="text-gray-400 text-sm mt-0.5">Financial health score</div>
            </div>
          </div>

          <p className="text-gray-500 text-sm leading-relaxed">
            This report was generated from bank statement data provided by the applicant.
          </p>
        </div>

        {/* Report metadata */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-4 mb-6">
          <dl className="space-y-2">
            <div className="flex justify-between text-sm">
              <dt className="text-gray-400">Report ID</dt>
              <dd className="text-gray-600 font-mono text-xs">{report.verificationToken}</dd>
            </div>
            <div className="flex justify-between text-sm">
              <dt className="text-gray-400">Generated</dt>
              <dd className="text-gray-600">{formatDate(report.createdAt)}</dd>
            </div>
            <div className="flex justify-between text-sm">
              <dt className="text-gray-400">Type</dt>
              <dd className="text-gray-600">{report.reportType === 'SELF_REQUESTED' ? 'Financial Passport' : 'Application report'}</dd>
            </div>
          </dl>
        </div>

        {/* Footer */}
        <div className="text-center">
          <Link href="/" className="text-sm text-green-600 hover:text-green-700 font-medium transition-colors">
            Powered by LetSorted
          </Link>
          <p className="text-gray-300 text-xs mt-1">letsorted.co.uk</p>
        </div>

      </div>
    </div>
  )
}
